# Generated by Django 3.0.3 on 2020-02-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.PositiveSmallIntegerField(choices=[(0, 'BANK 1'), (1, 'BANK 2'), (2, 'BANK 3')], default=0)),
                ('deposit_term', models.PositiveSmallIntegerField(choices=[(0, '12'), (1, '24'), (2, '48')], default=0)),
                ('rate_of_interest_1', models.FloatField(blank=True, null=True)),
                ('rate_of_interest_2', models.FloatField(blank=True, null=True)),
                ('rate_of_interest_3', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecuringDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.PositiveSmallIntegerField(choices=[(0, 'BANK 1'), (1, 'BANK 2'), (2, 'BANK 3')], default=0)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('deposit_term', models.PositiveSmallIntegerField(choices=[(0, '12'), (1, '24'), (2, '48')], default=0)),
                ('rate_of_interest', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
